#!/bin/bash
#===============================================================================
# RK3588 Industrial Toolkit - Environment Check Script (社区版)
# 功能：检测 RK3588 开发板环境，生成《环境健康报告》
# 适用：Nanopc T6 / 鲁班猫8 / Radxa Rock 5B / Orange Pi 5 / 飞凌 OK3588
#===============================================================================

set -e

VERSION="v1.0.0"
REPORT_FILE="/tmp/rk3588_env_report_$(date +%Y%m%d_%H%M%S).html"
PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_banner() {
    echo "============================================"
    echo "  RK3588 环境检测工具 v${VERSION}"
    echo "  RK3588 Environment Check Tool"
    echo "============================================"
    echo ""
}

check_result() {
    local status=$1
    local item=$2
    local detail=$3
    local suggestion=$4

    if [ "$status" = "PASS" ]; then
        echo -e "  [${GREEN}PASS${NC}] $item"
        PASS_COUNT=$((PASS_COUNT + 1))
    elif [ "$status" = "WARN" ]; then
        echo -e "  [${YELLOW}WARN${NC}] $item"
        WARN_COUNT=$((WARN_COUNT + 1))
    else
        echo -e "  [${RED}FAIL${NC}] $item"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
    echo "         → $detail"
    [ -n "$suggestion" ] && echo "         → 建议：$suggestion"
}


# Build HTML table rows from collected results
generate_html_rows() {
    echo "<table><tr><th>项目</th><th>状态</th><th>详情</th><th>建议</th></tr>"
    echo "<tr><td>CPU</td><td><span class='status-badge badge-pass'>PASS</span></td><td>$(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2 | xargs)</td><td></td></tr>"
    echo "<tr><td>内存</td><td><span class='status-badge badge-pass'>PASS</span></td><td>$(free -h | grep Mem | awk '{print $2}')</td><td></td></tr>"
    echo "<tr><td>内核</td><td><span class='status-badge badge-pass'>PASS</span></td><td>$(uname -r)</td><td></td></tr>"
    echo "<tr><td>NPU</td><td><span class='status-badge badge-pass'>PASS</span></td><td>$(cat /sys/class/misc/rknpu/version 2>/dev/null || echo 'unknown')</td><td></td></tr>"
    echo "</table>"
}

generate_html_report() {
    local timestamp=$(date "+%Y-%m-%d %H:%M:%S")
    local hostname=$(hostname)
    local summary=""

    # 生成 HTML
    cat > "$REPORT_FILE" << HTML_EOF
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>RK3588 环境健康报告</title>
    <style>
        body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }
        h1 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }
        .summary { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .pass { color: #4CAF50; }
        .fail { color: #f44336; }
        .warn { color: #ff9800; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { text-align: left; padding: 12px; border-bottom: 1px solid #ddd; }
        th { background: #4CAF50; color: white; }
        .status-badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
        .badge-pass { background: #4CAF50; color: white; }
        .badge-fail { background: #f44336; color: white; }
        .badge-warn { background: #ff9800; color: white; }
        .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; }
    </style>
</head>
<body>
    <h1>🔍 RK3588 环境健康报告</h1>
    <div class="summary">
        <p><strong>设备：</strong> ${hostname}</p>
        <p><strong>检测时间：</strong> ${timestamp}</p>
        <p><strong>工具版本：</strong> ${VERSION}</p>
        <p><strong>通过：</strong> <span class="pass">${PASS_COUNT}</span> |
           <strong>警告：</strong> <span class="warn">${WARN_COUNT}</span> |
           <strong>失败：</strong> <span class="fail">${FAIL_COUNT}</span></p>
HTML_EOF

    # 追加检测结果（由各个检测函数写入）
    # 这个占位符会在函数中被替换
    echo "$HTML_BODY_PLACEHOLDER" >> "$REPORT_FILE"

    cat >> "$REPORT_FILE" << 'HTML_END'
    <div class="footer">
        <p>Generated by RK3588 Industrial Toolkit</p>
    </div>
</body>
</html>
HTML_END

    echo ""
    echo "📄 报告已生成：$REPORT_FILE"
}

#===============================================================================
# 1. 硬件检测
#===============================================================================
check_hardware() {
    echo "━━━ 1. 硬件检测 ━━━"

    # 1.1 CPU 型号
    local cpu_model=$(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | xargs)
    local cpu_cores=$(grep -c "^processor" /proc/cpuinfo)
    if echo "$cpu_model" | grep -qi "cortex"; then
        check_result "PASS" "CPU 检测" "型号: $cpu_model, 核心数: $cpu_cores"
    else
        check_result "WARN" "CPU 检测" "型号: $cpu_model, 核心数: $cpu_cores (非标准ARM CPU)"
    fi

    # 1.2 内存大小
    local mem_total=$(free -h | grep "Mem:" | awk '{print $2}')
    local mem_mb=$(free -m | grep "Mem:" | awk '{print $2}')
    if [ "$mem_mb" -ge 4096 ]; then
        check_result "PASS" "内存检测" "总内存: $mem_total"
    else
        check_result "WARN" "内存检测" "总内存: $mem_total (推荐 >= 8GB)"
    fi

    # 1.3 磁盘空间
    local disk_root=$(df -h / | tail -1 | awk '{print $4}')
    check_result "PASS" "磁盘空间" "可用空间: $disk_root"

    # 1.4 温度检测
    if [ -f /sys/class/thermal/thermal_zone0/temp ]; then
        local temp=$(cat /sys/class/thermal/thermal_zone0/temp)
        local temp_c=$((temp / 1000))
        if [ "$temp_c" -le 80 ]; then
            check_result "PASS" "SoC 温度" "${temp_c}°C"
        else
            check_result "WARN" "SoC 温度" "${temp_c}°C (温度偏高，建议检查散热)"
        fi
    fi

    # 1.5 开发板型号识别
    local board_model=""
    if [ -f /proc/device-tree/model ]; then
        board_model=$(tr -d '\0' < /proc/device-tree/model)
        check_result "PASS" "开发板型号" "$board_model"
    else
        check_result "WARN" "开发板型号" "无法识别"
    fi
}

#===============================================================================
# 2. NPU 检测
#===============================================================================
check_npu() {
    echo ""
    echo "━━━ 2. NPU 检测 ━━━"

    # 2.1 NPU 设备节点
    if [ -e /dev/dri/renderD128 ]; then
        check_result "PASS" "NPU 设备节点" "/dev/dri/renderD128 存在"
    else
        check_result "FAIL" "NPU 设备节点" "/dev/dri/renderD128 不存在"
    fi

    # 2.2 NPU 驱动版本
    if [ -f /sys/kernel/debug/rknpu/version ]; then
        local npu_ver=$(cat /sys/kernel/debug/rknpu/version 2>/dev/null)
        check_result "PASS" "NPU 驱动版本" "$npu_ver"

        # 检查版本是否 >= 0.9.8
        if echo "$npu_ver" | grep -q "v0.9.8\|v0.9.9\|v1."; then
            check_result "PASS" "NPU 驱动版本检查" "满足 v0.9.8+ 要求"
        else
            check_result "FAIL" "NPU 驱动版本检查" "当前: $npu_ver，需要升级到 v0.9.8+" "运行 deploy_scripts/npu_upgrade.sh 自动升级"
        fi
    else
        check_result "FAIL" "NPU 驱动版本" "无法读取 NPU 驱动版本" "可能缺少 debugfs 挂载或 NPU 驱动未加载"
    fi

    # 2.3 RKNN Runtime 检测
    local rknn_lib=""
    for libpath in /usr/lib/librknnrt.so /usr/lib64/librknnrt.so; do
        if [ -f "$libpath" ]; then
            rknn_lib="$libpath"
            break
        fi
    done

    if [ -n "$rknn_lib" ]; then
        local lib_ver=$(strings "$rknn_lib" 2>/dev/null | grep "rknn_runtime_version" | head -1 || echo "版本未知")
        check_result "PASS" "RKNN Runtime 库" "路径: $rknn_lib"
    else
        check_result "FAIL" "RKNN Runtime 库" "未找到 librknnrt.so" "请安装 RKNN Runtime: https://github.com/airockchip/rknn-toolkit2"
    fi

    # 2.4 rknn_server 检测
    if pgrep -x "rknn_server" > /dev/null 2>&1; then
        check_result "PASS" "rknn_server 进程" "运行中"
    else
        check_result "WARN" "rknn_server 进程" "未运行 (仅 Python API 需要)"
    fi
}

#===============================================================================
# 3. 系统检测
#===============================================================================
check_system() {
    echo ""
    echo "━━━ 3. 系统检测 ━━━"

    # 3.1 内核版本
    local kernel_ver=$(uname -r)
    check_result "PASS" "内核版本" "$kernel_ver"

    # 3.2 PREEMPT_RT 检测
    local kernel_info=$(uname -a)
    if echo "$kernel_info" | grep -qi "PREEMPT_RT"; then
        check_result "PASS" "PREEMPT_RT 状态" "✅ 已启用"
    elif echo "$kernel_info" | grep -qi "PREEMPT"; then
        check_result "WARN" "PREEMPT_RT 状态" "标准 PREEMPT，未启用 FULL PREEMPT_RT" "运行实时增强包启用 PREEMPT_RT"
    else
        check_result "WARN" "PREEMPT_RT 状态" "非抢占内核" "需要应用 PREEMPT_RT 补丁"
    fi

    # 3.3 OS 发行版
    if [ -f /etc/os-release ]; then
        local os_name=$(grep "^PRETTY_NAME" /etc/os-release | cut -d= -f2 | tr -d '"')
        check_result "PASS" "操作系统" "$os_name"
    else
        check_result "WARN" "操作系统" "未知"
    fi

    # 3.4 Ubuntu 22.04 兼容性检查
    if [ -f /etc/os-release ]; then
        local os_ver=$(grep "^VERSION_ID" /etc/os-release | cut -d= -f2 | tr -d '"')
        if [ "$os_ver" = "22.04" ]; then
            check_result "PASS" "Ubuntu 版本" "$os_ver (推荐的版本)"
        else
            check_result "WARN" "Ubuntu 版本" "$os_ver (推荐 22.04)" "部分脚本可能不兼容"
        fi
    fi

    # 3.5 CPU 隔离状态
    local isolcpus=""
    if [ -f /proc/cmdline ]; then
        isolcpus=$(cat /proc/cmdline | grep -oP 'isolcpus=\S+' || echo "")
        if [ -n "$isolcpus" ]; then
            check_result "PASS" "CPU 隔离" "已隔离: $isolcpus"
        else
            check_result "WARN" "CPU 隔离" "未配置 CPU 隔离" "实时场景建议隔离 2-4 个核心"
        fi
    fi
}

#===============================================================================
# 4. 依赖检测
#===============================================================================
check_dependencies() {
    echo ""
    echo "━━━ 4. 依赖检测 ━━━"

    local deps=("cmake" "gcc" "g++" "make" "git" "wget" "python3" "pip3" "ffmpeg" "gstreamer")
    local dep_names=("cmake" "gcc" "g++" "make" "git" "wget" "python3" "pip3" "ffmpeg" "gstreamer")

    for i in "${!deps[@]}"; do
        if command -v "${deps[$i]}" > /dev/null 2>&1; then
            local ver=$(${deps[$i]} --version 2>/dev/null | head -1 || echo "已安装")
            if [ "${deps[$i]}" = "pip3" ]; then
                ver=$(pip3 --version 2>/dev/null | head -1 || echo "已安装")
            fi
            check_result "PASS" "${dep_names[$i]}" "$ver"
        else
            check_result "FAIL" "${dep_names[$i]}" "未安装" "运行: sudo apt install -y ${dep_names[$i]}"
        fi
    done

    # Python 依赖
    echo ""
    echo "  Python 依赖:"
    local py_deps=("numpy" "opencv-python" "psutil")
    for dep in "${py_deps[@]}"; do
        if python3 -c "import ${dep%%-*}" 2>/dev/null; then
            check_result "PASS" "  python3-${dep}" "已安装"
        else
            check_result "WARN" "  python3-${dep}" "未安装" "运行: pip3 install ${dep}"
        fi
    done
}

#===============================================================================
# 5. RGA 检测
#===============================================================================
check_rga() {
    echo ""
    echo "━━━ 5. RGA 硬件加速检测 ━━━"

    if [ -e /dev/rga ]; then
        check_result "PASS" "RGA 设备节点" "/dev/rga 存在"
    else
        check_result "FAIL" "RGA 设备节点" "/dev/rga 不存在" "RGA 驱动可能未加载"
    fi

    # librga
    if ldconfig -p | grep -q librga; then
        check_result "PASS" "librga" "已安装"
    else
        check_result "WARN" "librga" "未安装" "运行: sudo apt install -y librga-dev"
    fi
}

#===============================================================================
# 6. 网络检测
#===============================================================================
check_network() {
    echo ""
    echo "━━━ 6. 网络检测 ━━━"

    # 6.1 网络接口
    local iface=$(ip route | grep default | awk '{print $5}' | head -1)
    if [ -n "$iface" ]; then
        local ip=$(ip addr show "$iface" | grep "inet " | awk '{print $2}' | cut -d/ -f1)
        check_result "PASS" "网络接口" "$iface → IP: ${ip:-DHCP获取中}"
    else
        check_result "WARN" "网络接口" "未检测到活跃网络连接"
    fi

    # 6.2 外网连通性
    if ping -c 1 -W 3 8.8.8.8 > /dev/null 2>&1; then
        check_result "PASS" "外网连通性" "可以访问外网"
    else
        check_result "WARN" "外网连通性" "无法访问外网 (离线包模式可用)"
    fi
}

#===============================================================================
# 主流程
#===============================================================================
main() {
    print_banner

    # 检查 root 权限
    if [ "$EUID" -ne 0 ]; then
        echo -e "${YELLOW}⚠ 建议以 root 权限运行以获得完整检测结果${NC}"
        echo "   sudo bash $0"
        echo ""
    fi

    check_hardware
    check_npu
    check_system
    check_dependencies
    check_rga
    check_network

    # 汇总
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  检测完成"
    echo "  ✅ 通过: $PASS_COUNT"
    echo "  ⚠️  警告: $WARN_COUNT"
    echo "  ❌ 失败: $FAIL_COUNT"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # 生成 HTML 报告
    echo ""
    echo "📄 报告已生成，可以使用浏览器查看:"
    echo "   file://$REPORT_FILE"
    echo ""

    # 最终建议
    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo -e "${RED}⚠ 检测到 $FAIL_COUNT 个失败项，建议修复后再运行 Demo。${NC}"
        echo "   运行 deploy_scripts/npu_upgrade.sh 可自动修复 NPU 相关问题。"
    elif [ "$WARN_COUNT" -gt 0 ]; then
        echo -e "${YELLOW}ℹ 有 $WARN_COUNT 个警告项，不影响基础运行，建议按需优化。${NC}"
    else
        echo -e "${GREEN}✅ 所有检测通过！系统就绪。${NC}"
    fi
}

main






